### ISSUE TITLE
Why void class should be ignored during accuracy calculation if during training it was considered?

### ISSUE THREAD

**Issue by blaxe05** [lexfridman/deepcars#15]
Hope you could give some insight why the void class or background class should be ignore during confusion matrix calculation since during training void class is included?

**Comment by ghost** [comment]
Including the background class in Training allows the model to become familiar (or learn) the surrounding environment. This in itself helps in reducing confusion since many objects in that environment (buildings, trees, mountains, etc.) may not directly be affecting Driving. In assessing Performance (Accuracy) however, we want to ensure that objects involved in the Driving scenario (Pedestrians, Car, Motorcycle, etc.) are detected and identified accurately. That is why the background class is usually not included at this stage. 

It must, however, be noted that many researchers choose to do away with the background class altogether (even in Training). They instead ensure that their class register is as exhaustive as possible, and rely on the confidence probability (Pc) that an object of interest (for Driving) is present in the bounding box during Object Detection.
